#!/bin/bash

# Build server jar but skip unit test
(cd service-status-server; mvn clean install -Dmaven.test.skip=true)
cp service-status-server/target/microservice-service-status-server-1.0.0.jar topology/images/server/server.jar
