#!/bin/bash

./build

(cd ./topology; docker-compose down --volumes)
(cd ./topology; docker-compose up --build -d)

(cd ./topology; ./wait-for-it.sh -h localhost -p 8080 -t 30)
(cd ./service-status-specs; mvn clean install)
