version: '2.1'

services:
    database:
        build: ./images/mysql
        container_name: microservice-db-test
        restart: always
        expose:
            - '3306'
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"USE microservice_test;\""
            interval: 4s
            timeout: 1s
            retries: 5
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: 'microservice_test'
    server:
        build:
            context: ./images/server
        container_name: service_server
        depends_on:
            database:
                condition: service_healthy
        image: amt/status-server
        environment:
            SPRING_DATASOURCE_URL: 'jdbc:mysql://database:3306/microservice_test'
        ports:
            - '8080:8080'
        restart: always
     
    mockserver:
        container_name: mock_server
        image: rodolpheche/wiremock
        restart: always
        ports:
            - '8081:8080'
