version: '2.1'

services:
    database:
        build: ./images/mysql
        container_name: microservice-db
        restart: always
        expose:
            - '3306'
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"USE microservice;\""
            interval: 4s
            timeout: 1s
            retries: 10
        environment:
            MYSQL_USER: servicestatus
            MYSQL_PASSWORD: servicestatus
            MYSQL_DATABASE: 'microservice'
    server:
        build:
            context: ./images/server
        container_name: service_server
        depends_on:
            database:
                condition: service_healthy
        image: amt/status-server
        environment:
            SPRING_DATASOURCE_URL: 'jdbc:mysql://database:3306/microservice?useSSL=false'
        ports:
            - '8080:8080'
        restart: always
