#!/bin/bash

./build

(cd ../topology; docker-compose -f docker-compose-test.yml down --volumes)
(cd ../topology; docker-compose -f docker-compose-test.yml up --build -d)

cd ../service-status-server
mvn test
