#!/bin/bash

./build

(cd ../topology; docker-compose -f docker-compose-test.yml down --volumes)
(cd ../topology; docker-compose -f docker-compose-test.yml up --build -d)

cd ../service-status-tests

#mvn test -Dio.lozzikit.service-status.server.url=http://localhost:8080/api

while [ 1 ]
do
     curl -s 'localhost:8080/api' > /dev/null
     if [ $? == 0 ]
     then
         break
     fi
     echo Waiting for main server to be online.....
     sleep 1
done

npm test
